### PR TITLE
Document adding server health messages

### PR DESCRIPTION
**Pull request by arvindsv**
Documentation for https://github.com/gocd/gocd/pull/4536.

### CODE REVIEW

**Comment by arvindsv** [comment]
@maheshp Made the changes we talked about (specifying request version). It looks like this now:

screenshot-2018-4-11 gocd notification plugin api reference

**Comment by ketan** [comment]
Do we need to add an "available since" on the request?

>

**Comment by arvindsv** [comment]
Yes, you're right. Done. Looks like this now:

screenshot-2018-4-11 gocd notification plugin api reference 1

**Comment by arvindsv** [comment]
Oops. Sorry. Forgot about adding that. I've reworded that message a bit. I'll merge it now.

image

**Pull request merged**
